version: '3'
services:
  my-app:
    image: lyricnrhyme/articles-products-and-express:${IMAGE_VERSION}-local
    command: ["./node_modules/.bin/nodemon", "app.js"]
    container_name: this-app
    volumes:
      - ".:/app/:rw"
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      - "${EXPRESS_HOST_PORT}:${EXPRESS_CONTAINER_PORT}"
    networks:
      - this-app-network

networks:
  this-app-network:
